[package]
name = "pomodoro"
version = "0.1.0"
authors = ["FreeFlyFall"]
edition = "2021"

[dependencies]
rodio = "0.17.1"
regex = "1"
libmath = "0.2.1"
tokio = { version = "1.27.0", features = ["full"] }
